name: master
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Install the stuff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1

      - name: Download binaries
        run: |
          set -eEuo pipefail
          bin/artifacts --download

      - name: Run Tests
        run: |
          set -eEuo pipefail
          export LD_LIBRARY_PATH=lib
          [[ "$(bin/bar)" = "The answer is: 42" ]]

      - name: Promote master to stage-1
        run: |
          set -eEuo pipefail
          git push master origin/stage-1
