name: Actions Test
on: [push]
jobs:
  test:
    name: Install the stuff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1

      - name: Download binaries
        run: |
          set -eEuo pipefail
          
          # Parse the git log and find the artifacts for each submodule.
          # The function expects that the git log contains entries like
          #   Update foo http://www.download.com/foo.tar.gz
          # It traverses the whole commit log and finds the latest entry for
          # each submodule.
          parse-log() {
              local -r aggregate='BEGIN {FS=OFS=SUBSEP=" "}{arr[$1] = $2} END {for (i in arr) print i,arr[i]}'
              local -r pattern='Update .+ https?://[a-zA-Z0-9./?=_-]*'
              git log --reverse --pretty=%B | grep -E "$pattern" | while read -r x; do
                  echo $x | cut -d' ' -f2,3
              done | awk "$aggregate"
          }
          
          # Download artifacts for each submodule
          parse-log | while read -r submodule url; do
              echo "Downloading $url" >&2
              curl --silent --fail $url | tar xzv
          done

      - name: Run Tests
        run: |
          set -eEuo pipefail
          set -x
          export LD_LIBRARY_PATH=lib
          [[ "$(bin/bar)" = "The answer is: 42" ]]
