name: Actions Test
on: [push]
jobs:
  install:
    name: Install the stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: github-actions-test/fetch-binaries-action@master
