name: Actions Test
on: [push]
jobs:
  test:
    name: Install the stuff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1

      - name: Download binaries
        run: |
          set -eEuo pipefail
          bin/artifacts | while read -r submodule url; do
              echo "Downloading $url" >&2
              curl --silent --fail $url | tar xzv
          done

      - name: Run Tests
        run: |
          set -eEuo pipefail
          set -x
          export LD_LIBRARY_PATH=lib
          [[ "$(bin/bar)" = "The answer is: 42" ]]
